
all:
	cd jffs2; make clean; make; cp mkfs.jffs2 ../bin;
	cd mtd-utils*/ubi-utils; make clean; make; cp ubinize ../../bin;
	cd mtd-utils*/mkfs.ubifs; make clean; make; cp mkfs.ubifs ../../bin;

clean:


